export const SET_LOGIN_SUCCESS = 'LOGIN/SET_LOGIN_SUCCESS'
export const SET_LOGIN_ERROR = 'LOGIN/SET_LOGIN_ERROR'
export const SET_ISLOGIN = 'LOGIN/ISLOGIN'

// home banner
export const SET_HOMEPAGE_BANNER = 'HOMEPAGE/SETBANNER'